export { Hero } from './Hero/Hero'
export { Skills } from './Skills/Skills'
export { About } from './About/About'
export { Experience } from './Experience/Experience'
export { Projects } from './Projects/Projects'
export { Testimonial } from './Testimonial/Testimonial'
export { Form } from './Form/Form'